name: build_docker

on:
  workflow_run:
    workflows: [ci]
    types:
      - completed
  release:
    types: [created] # 表示在创建新的 Release 时触发

jobs:
  build_docker:
    name: Build docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - run: |
          echo 本次构建的版本为：${{ github.ref_name }}
          env

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Build Web
        id: build_web
        run: | 
          npm i
          npm run build

      - name: Build Service
        id: build_service
        run: | 
          cd service 
          npm i 
          npm run build
          cd ../
      
      - name: Show List
        id: show_list
        run: | 
          ls -la
          cd .next
          ls -la
          cd ../service/dist
          ls -la
          cd ../../

      - name: Get version number
        id: version
        run: |
          echo "::set-output name=version::$(node -p "require('./package.json').version")"

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/chatgpt-plus:${{ steps.version.outputs.version }}
            ${{ secrets.DOCKERHUB_USERNAME }}/chatgpt-plus:latest
